// Interactive setup: asks for each credential in plain language and writes
// .env for you. Run with: npm run setup
//
// Note: input isn't masked (it'll show on screen and land in your terminal's
// scrollback/history). If that's a concern on a shared machine, clear your
// terminal history afterward.
import readline from "readline";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.join(__dirname, "..", ".env");

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((resolve) => rl.question(q, (a) => resolve(a.trim())));

async function main() {
  console.log(`
School Hub setup
----------------
This asks for each credential once and saves them to a local .env file on
this machine. Nothing you enter is sent anywhere else.
`);

  if (fs.existsSync(envPath)) {
    const overwrite = await ask(".env already exists -- overwrite it? (y/N): ");
    if (overwrite.toLowerCase() !== "y") {
      console.log("Left your existing .env untouched.");
      rl.close();
      return;
    }
  }

  console.log("\n-- Classification (free) --");
  console.log("Get a free key at https://aistudio.google.com/apikey (no card needed)");
  const geminiKey = await ask("Gemini API key: ");

  console.log("\n-- Google Calendar --");
  console.log("Create an OAuth Client ID (type: Desktop app) at https://console.cloud.google.com");
  console.log("with the Calendar API enabled on the project.");
  const googleClientId = await ask("Google OAuth Client ID: ");
  const googleClientSecret = await ask("Google OAuth Client Secret: ");
  const calendarId =
    (await ask("Calendar ID to sync into (leave blank for your main calendar): ")) || "primary";

  console.log("\n-- Approval emails --");
  console.log("Create an App Password at https://myaccount.google.com/apppasswords");
  console.log("(needs 2-factor authentication turned on for your Google account first)");
  const gmailAddress = await ask("Your Gmail address: ");
  const gmailAppPassword = await ask("Gmail App Password: ");
  const notifyEmail =
    (await ask(`Send approval emails to (press enter to use ${gmailAddress}): `)) || gmailAddress;

  console.log("\n-- ClassDojo (press enter to skip if you don't use it) --");
  const dojoEmail = await ask("ClassDojo email: ");
  const dojoPassword = dojoEmail ? await ask("ClassDojo password: ") : "";

  console.log("\n-- MyChildAtSchool (press enter to skip if you don't use it) --");
  const mcasEmail = await ask("MyChildAtSchool email: ");
  const mcasPassword = mcasEmail ? await ask("MyChildAtSchool password: ") : "";

  console.log("\n-- Class Charts (press enter to skip) --");
  console.log("Note: this needs each child's own pupil login code + date of birth,");
  console.log("not your parent account -- Class Charts' parent site has a security");
  console.log("check this can't get past. Format: Name,code,DOB;Name,code,DOB");
  const classChartsStudents = await ask("Children (leave blank to skip): ");

  const env = `# Generated by 'npm run setup' on ${new Date().toISOString().slice(0, 10)}

GEMINI_API_KEY=${geminiKey}
AUTO_ADD_THRESHOLD=80

GOOGLE_CLIENT_ID=${googleClientId}
GOOGLE_CLIENT_SECRET=${googleClientSecret}
GOOGLE_CALENDAR_ID=${calendarId}

GMAIL_ADDRESS=${gmailAddress}
GMAIL_APP_PASSWORD=${gmailAppPassword}
NOTIFY_EMAIL=${notifyEmail}

DASHBOARD_PORT=4173
DASHBOARD_PUBLIC_URL=

CLASSCHARTS_STUDENTS=${classChartsStudents}

CLASSDOJO_EMAIL=${dojoEmail}
CLASSDOJO_PASSWORD=${dojoPassword}

MCAS_SCHOOL_ID=
MCAS_EMAIL=${mcasEmail}
MCAS_PASSWORD=${mcasPassword}
`;

  fs.writeFileSync(envPath, env, { mode: 0o600 });
  console.log(`\nSaved to ${envPath}\n`);
  console.log("Next steps:");
  console.log("  1. npm run authorize-google   (connects your Google Calendar)");
  console.log("  2. npm run install-service    (sets everything running automatically)");
  console.log("  3. npm run doctor             (checks everything is working)");

  rl.close();
}

main();
